### ISSUE TITLE
Installing removed dependency

### ISSUE THREAD

**Issue by AIDungeonWiXAnon** [AIDungeonpastes/Clover-Edition-Installer#4]
https://github.com/AIDungeonpastes/Clover-Edition-Installer/blob/b993d9a7bef3c3d34d61f9a2a16da2fae07892af/main.bat#L9
With cloveranon/Clover-Edition#62 pyjarowinkler has been removed as a dependency for Clover Edition.

**Comment by AIDungeonpastes** [comment]
Thanks for letting me know, fixed.
